---
# - name: LAMP server installation v2
#   hosts: pie3
#   apt:
- name: Install Apache
  hosts: pie3
  become: yes
  become_method: sudo

  roles:
  - webservers

#       - apache2
#       # - mysql-common
#       # - mysql-server
#       - php
#       - php-mysql
#     state: present
#   become: yes
#   become_method: sudo

  #- name: DEPRECATED LAMP server installation
  #apt: 'pkg={{item}} state=present'
  #with_items:
  #- apache2
  #- php
- name: Install db
  hosts: pie3
  become: yes
  become_method: sudo

  roles:
  - db

# - name: Correct ownership
#   hosts: pie3
#   file:
#     path: /var/www/html
#     state: directory
#     owner: pi
#     group: www-data
#     mode: 0770

# - name: ensure httpd is running
#   hosts: pie3
#   systemd:
#       name: apache2
#       state: started
#   become: yes
#   become_method: sudo
# - debug: var=results
