---
- hosts: raspberrypi
  remote_user: pi
  tasks:
      - name: ensure httpd is running
        systemd:
            name: apache2
            state: started
        become: yes
        become_method: sudo

      - debug: var=results

