---
- hosts: raspberrypi
  remote_user: pi
  tasks:
    - name: stop httpd
      systemd:
          name: apache2
          state: stopped
      become: yes
      become_method: sudo

    - name: stop mysql-server
      systemd:
        name: mysqld
        state: stopped
      become: yes
      become_method: sudo
